#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor Virtual1 -d I II III IV V 
bspc monitor Virtual2 -d VI VII VIII IX X

#window
bspc config window_gap            25
bspc config split_ratio           0.5

#border
bspc config border_width          2
bspc config focused_border_color	\#ffaf9c

#monocle
bspc config borderless_monocle    false
bspc config single_monocle        true
bspc config gapless_monocle       false

#padding
bspc config top_padding		        -25
#uncomment if gapless_monocle
#bspc config top_monocle_padding   25

#configure second monitor
#xrandr --output Virtual2 --primary --pos 1920x0

#launch polybar
$HOME/.config/polybar/launch.sh
